### ISSUE TITLE
Add support for nvim-tree.lua

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [savq/melange-nvim#34]
i noticed that the melange colors are weird in [nvim tree](https://github.com/kyazdani42/nvim-tree.lua) when it is loaded in `init.lua` using
```lua
vim.cmd('colorscheme melange')
```

loaded in `init.lua`
![image](https://user-images.githubusercontent.com/79387351/148625388-41e76100-2d9f-4d75-9318-37396e54d374.png)

loaded after init using `:colorscheme melange`
![image](https://user-images.githubusercontent.com/79387351/148628691-ef33e411-c2b1-488d-9fae-03ce6ea402d0.png)

can this be solved?

**Comment by savq** [comment]
Reading the nvim-tree.lua docs:

> Syntax highlighting uses g:terminal_color_ from colorschemes, fallbacks to ugly colors otherwise.

So the problem is likely that melange doesn't set these variables explicitly.
