### ISSUE TITLE
Installing using vim-plug

### ISSUE THREAD

**Issue by mbledkowski** [savq/melange-nvim#41]
Hi, I am new to (neo)vim. Is there any way to install this theme using vim-plug?

**Comment by savq** [comment]
Yes. First write in your .vimrc/init.vim

```vim
Plug 'junegunn/vim-easy-align'
```

Reload your config (`:source $MYVIMRC`) and run `:PlugInstall`. After that, you add to your config

```vim
set termguicolors
colorscheme melange
```

And that should do it.
