### ISSUE TITLE
Add support for adding custom keyword to highlight group

### ISSUE THREAD

**Issue by BrandonBlankerLim-it** [savq/melange-nvim#42]
for example i want to add `self` keyword to highlight groups same with the `function` keyword

**Comment by savq** [comment]
If you want to add highlighting for certain keywords you have to use the [`:syntax` API](https://neovim.io/doc/user/syntax.html#syntax). See also [`:help usr_44.txt`](https://neovim.io/doc/user/usr_44.html#usr_44.txt). This is usually done by filetype plugins, not colorschemes themselves.

Sorry for not answering this sooner.
