### ISSUE TITLE
Color of line numbers and whitespaces are too bright

### ISSUE THREAD

**Issue by tudor07** [savq/melange-nvim#53]
The color of line numbers and of the invisible characters (like empty space and the vertical lines) is way too bright. In the previous version the color was better.

![Screenshot 2023-01-24 at 17 57 36](https://user-images.githubusercontent.com/7441453/214343137-33389969-95e0-4de2-8081-b6227bf9319a.jpg)

**Comment by tudor07** [comment]
I guess no plan to allow overwriting colors?

**Comment by savq** [comment]
I added the `IndentBlanklineChar` highlight group in #54 

> I guess no plan to allow overwriting colors either?

You can use the Lua API for that. In this case, if you want to darken `Whitespace`, you could link `Whitespace` to `IndentBlanklineChar`:

```lua
vim.cmd.colorscheme 'melange'

local id = vim.api.nvim_create_augroup('HighlightOverrides', {})
vim.api.nvim_create_autocmd('BufEnter', {
    group = id,
    pattern = '*',
    callback = function()
        vim.api.nvim_set_hl(0, 'Whitespace', { link = 'IndentBlanklineChar' })
    end,
})
```

**Comment by tudor07** [comment]
![Screenshot 2023-01-31 at 11 13 48](https://user-images.githubusercontent.com/7441453/215718003-b5206aec-1aba-4c40-858c-d87d39d27dc2.jpg)
![Screenshot 2023-01-31 at 11 14 17](https://user-images.githubusercontent.com/7441453/215718105-2ced61cd-7f80-4867-9696-098835c3676b.jpg)

That... almost did the trick. Some whitespace are with new color (the brighter ones) and some are with the old color.
When I place the cursor inside the context of the method some whitespaces change the color from new to old one.
Not sure how to make all of them the old color all the time.

**Comment by savq** [comment]
That's the intended behavior (I think?). See [hl-IndentBlanklineContextChar](https://github.com/lukas-reineke/indent-blankline.nvim/blob/8299fe7703dfff4b1752aeed271c3b95281a952d/doc/indent_blankline.txt#L69)

**Comment by tudor07** [comment]
I just wanted all the whitespaces to be the old color. Btw feel free to close this ticket if this is not something you are interested in doing, I realise this is just a personal preference of mine.

**Comment by savq** [comment]
Yeah, sorry. I misunderstood the question, and also misunderstood how indent-blankline worked. When the docs say:

> Default: takes guifg color from 'Whitespace'

The really mean it. These highlight groups are not linked, but manually extended using `synID*` functions (wtf?) Anyways, I think they do that to set `nocombine`. 3c430b644a6fe6789db99d0c7d70ba7a5ccd57ba should probably highlight all the indent-related whitespace the same.

Let me know if that works.

**Comment by tudor07** [comment]
Wow, it works now, thank you so much
