### ISSUE TITLE
Kitty terminal support improvement

### ISSUE THREAD

**Issue by ThorstenRhau** [savq/melange-nvim#58]
Hello
Would it be possible to add "cursor_text_color" in a contrasting color to the Kitty terminal themes? With this parameter missing the block cursor in nvim becomes just a dark block that hides the character behind it.

I tried adding "cursor_text_color #F1F1F1" to the light Kitty theme and that fixed the problem for the light theme.

**Comment by savq** [comment]
Sure. I don't really use kitty, but I found this in the [docs](https://sw.kovidgoyal.net/kitty/conf/#cursor-customization):

> cursor_text_color
>
> cursor_text_color #111111
>
> The color of text under the [cursor](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor). If you want it rendered with the background color of the cell underneath instead, use the special keyword: background. Note that if cursor is set to none then this option is ignored.

So to invert the colors of the cursor using `background` should be enough right?

Can you let me know if that work to add it to the [template](https://github.com/savq/melange-nvim/blob/2c8250c435279638b5a244acfaf9fcdb702a45cc/lua/melange/build.lua#L140)?

**Comment by ThorstenRhau** [comment]
Works well on my setup. I run Kitty on macOS.

**Comment by savq** [comment]
I missed the part where it says that setting `cursor none` will reverse colors, which is more consistent with Alacritty (and Wezterm with `force_reverse_video_cursor`). I'll add that instead.
