### ISSUE TITLE
No Cursor in Noice Commandline

### ISSUE THREAD

**Issue by Quacktiamauct** [savq/melange-nvim#67]
In the Noice the cursor in the commandline is invisible, since the `Cursor` highlight in melanage is not set and `NoiceCursor` links to it.
This can be fixed by either setting the `Cursor` or `NoiceCursor` to something, but is there is reason `Cursor` has been left unset?

Current output:
<img width="594" alt="image" src="https://github.com/savq/melange-nvim/assets/32653278/0adb6bae-5c2e-43af-9466-1658ed631b4f">

With `NoiseCursor = {bg = a.fg, fg = a.bg}`:
<img width="522" alt="image" src="https://github.com/savq/melange-nvim/assets/32653278/194b0eed-13b3-4fe3-99c2-28fd6ccddd91">

**Comment by savq** [comment]
> the Cursor highlight in melanage is not set

Neovim sets `Cursor` by default. What do you get when you run `:highlight Cursor` ?

**Comment by Quacktiamauct** [comment]
Currently just `Cursor        xxx guifg=bg guibg=fg`, which is the same as if ran with `-u NONE` without any color scheme at all.

**Comment by savq** [comment]
I don't understand what the problem is here.

If `NoiceCursor` links to `Cursor`, and `Cursor` is set to the default, then the cursor should appear just like it does in the command line.

If noice does something different to render the cursor, then that's a problem there, not here.

**Comment by Quacktiamauct** [comment]
Okay, so funnily enough if I set `hi guifg=bg guibg=fg` then noice's cursor appears correctly.  

Doing a `hi clear` also wipes the noice cursor.
Most other color schemes seem to define `Cursor` so noice just links to that. The only two solutions I really see is either providing explicit setting `Cursor` or providing `NoiceCursor` highlight for compatiblity.

**Comment by savq** [comment]
See https://github.com/folke/noice.nvim/discussions/596
