### ISSUE TITLE
[feature request] add transparency?

### ISSUE THREAD

**Issue by baggiponte** [savq/melange-nvim#68]
just found out about melange thanks to [this blog post](https://www.jonashietala.se/blog/2023/10/01/rewriting_my_neovim_config_in_lua/), and I totally stand by this:

> the only colorscheme I’ve found that I didn’t eject in horror after 5 minutes, except for gruvbox

Would you consider adding transparency?

**Comment by savq** [comment]
I'm not planning on adding more configuration options to Melange in the near future. You can modify Melange using existing features, that is, you can override highlight groups in an autocommand that runs when melange is loaded.

In Vimscript:

```vim
augroup OverrideMelange
  autocmd!
  autocmd ColorScheme melange highlight Normal guibg=NONE
augroup END
```

Or in Lua:

```lua
local group = vim.api.nvim_create_augroup('OverrideMelange', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  pattern = 'melange',
  callback = function() vim.api.nvim_set_hl(0, 'Normal', { bg = 'NONE' }) end,
  group = group,
})
```

**Comment by baggiponte** [comment]
Thanks!
