### ISSUE TITLE
Cursor "disappears" in noice.nvim's popup window

### ISSUE THREAD

**Issue by brg1ng** [savq/melange-nvim#81]
<img width="1512" alt="图片" src="https://github.com/savq/melange-nvim/assets/115389762/d354de25-992f-43aa-9841-0f19ff093c09">

The cursor disappears in noice.nvim's popup window.

**Comment by brglng** [comment]
It looks the issue is fixed in the latest version, so closing.

**Comment by savq** [comment]
Hi @brg1ng. Sorry for not going over this issue. I think someone had already reported a similar issue, but I didn't find anything we could do on our end. I'm glad this was fixed on noice.
