### ISSUE TITLE
g:terminal_ansi_colors

### ISSUE THREAD

**Issue by barrett-ruth** [savq/melange-nvim#83]
Hello,

Love the color scheme. Is there a defined set of 16 RRGGBB values that correlate to the ANSI colors used by the terminal? I believe it is also best practice for colorschemes to include this (`e $VIMRUNTIME/colors/README.txt`). 

I see [this file here](https://github.com/savq/melange-nvim/blob/master/term/kitty/melange_light.conf) - does this match those exact values?

Thanks.

**Comment by savq** [comment]
It seems `g:terminal_ansi_colors` is only documented in Vim, not Neovim. But it's a good idea. I'll try and look into why neovim hasn't ported it over.

The alternative is using the [`g.terminal_color_x`](https://neovim.io/doc/user/nvim_terminal_emulator.html#terminal-config) variables defiend at the bottom of [colors/melange.lua](https://github.com/savq/melange-nvim/blob/master/colors/melange.lua#L379-L395). 

The terminal themes generator uses the function [`get_palette`](https://github.com/savq/melange-nvim/blob/master/lua/melange/build.lua#L27-L59) to turn melange naming convention into something closer to ANSI naming conventions.

**Comment by barrett-ruth** [comment]
Nevermind. The alternative you have is more up to date. You could just set the table equal to `g:terminal_ansi_colors` for completeness, though. Thanks!
